language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: igorbrehm-github
    token:
      secure: 1ed0205aded2aa40fab0f456f25d89324545b8a7
script:
  - sonar-scanner
